export const metadata = {
  title: "Legal & Disclaimer",
};

export default function LegalPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-3xl prose prose-sm md:prose-base prose-neutral dark:prose-invert">
      <h1>Legal &amp; Disclaimer</h1>

      <h2>Disclaimer</h2>
      <p>
        The Lighting Controls Planner is a design aid provided by A+ Lighting
        LLC to help users develop conceptual lighting controls designs. It is{" "}
        <strong>NOT</strong> a compliance certification, engineering stamp, or
        substitute for review by a licensed engineer or Authority Having
        Jurisdiction (AHJ).
      </p>
      <p>
        Outputs are based on ASHRAE 90.1-2019 requirements as interpreted by A+
        Lighting LLC. Local codes, amendments, and AHJ rulings may impose
        additional or different requirements. Users are solely responsible for
        verifying all outputs against applicable codes and for obtaining
        required approvals, permits, and engineer sign-offs prior to
        installation.
      </p>
      <p>
        A+ Lighting LLC makes no warranty of accuracy, completeness, or fitness
        for any particular purpose. In no event shall A+ Lighting LLC be liable
        for damages arising from use of this tool.
      </p>
      <p>
        Final construction documents, manufacturer approvals, and installation
        must be performed by qualified parties.
      </p>

      <h2>Terms of Use</h2>
      <p className="text-sm text-muted-foreground">
        Full Terms of Use and Privacy Policy coming soon. Current scope of use:
        the free public tool does not collect personal data, does not require an
        account, and uses privacy-friendly analytics only. Intellectual property
        in the tool, generated text, and templates is owned by A+ Lighting LLC;
        outputs generated by users remain the user&rsquo;s property, subject to
        these terms and the disclaimer above.
      </p>

      <h2>Attribution</h2>
      <p className="text-sm text-muted-foreground">
        ASHRAE 90.1-2019 section references are used for educational and
        reference purposes. The full standard is published by ASHRAE and is
        separately copyrighted. Requirement descriptions in this tool are
        paraphrased summaries, not reproductions of ASHRAE text. IES
        illumination recommendations are cited from the applicable IES
        publications; full standards are published separately by IES.
      </p>

      <h2>Contact</h2>
      <p>
        Questions, corrections, or feedback?{" "}
        <a href="https://apluslightingllc.com/contact">Contact A+ Lighting</a>.
      </p>
    </div>
  );
}
